"""Constants for OASE FM-Master Local."""

DOMAIN = "oase_fm"
CONF_HOST = "host"
CONF_PASSWORD = "password"
PLATFORMS = ["switch", "light"]
DATA_CLIENT = "client"
DATA_COORDINATOR = "coordinator"
UPDATE_INTERVAL_SECONDS = 30
SOCKET_COUNT = 4

# Current EasyControl O-Net v2 packet types.
REQUEST_TCP_CALLBACK = 0x1400
REQUEST_TCP_CALLBACK_REPLY = 0x14FF
CHECK_PASSWORD = 0x9F00
CHECK_PASSWORD_REPLY = 0x9FFF
GET_LIVE_SCENE = 0xC500
GET_LIVE_SCENE_REPLY = 0xC5FF
SET_LIVE_SCENE = 0xC400
SET_LIVE_SCENE_REPLY = 0xC4FF

TCP_CALLBACK_PORT = 5999
UDP_PORT = 5959
TLS_CERT_COMMON_NAME = "com.oase.easycontrol"
